### ISSUE TITLE
Provide enhanced implementation.

### ISSUE THREAD

**Issue by hrsh7th** [tami5/vim-iced-compe#1]
It's worked version of this source.

```viml
if exists('g:loaded_vim_iced_compe')
  finish
endif
let g:loaded_vim_iced_compe = 1

function! s:get_metadata() abort
  return { 'priority': 1000, 'dup': 1, 'filetypes': ['clojure'] }
endfunction

function! s:datermine(context) abort
  let l:offset = compe#pattern#get_offset(a:context, '[[:alnum:]!$&*\-_=+:<>./?]\+$')
  if l:offset > 0
    return {
    \   'keyword_pattern_offset': l:offset
    \ }
  end
  return {}
endfunction

function! s:complete(args) abort
  if !iced#repl#is_connected()
    return a:args.abort()
  endif

  if !iced#nrepl#check_session_validity(v:false)
    return a:args.abort()
  endif

  call iced#complete#candidates(a:args.input, { candidates ->
  \   a:args.callback({
  \     'items': candidates
  \   })
  \ })
endfunction

let s:source = {
\   'get_metadata': function('s:get_metadata'),
\   'datermine': function('s:datermine'),
\   'complete': function('s:complete'),
\ }

call compe#source#vim_bridge#register('iced', s:source)
```

**Comment by kkharji** [comment]
Hey @hrsh7th, Did this worked for you, I just tested out but it no completion.

@liquidz suggested the following 

- 1915a52#diff-e7c04951d40c1c24b7dde8bcd0db6c04f2e0911332a0efde5881f5f6c9f1a7bfR29-R30
a:args should be a:context.
- 1915a52#diff-e7c04951d40c1c24b7dde8bcd0db6c04f2e0911332a0efde5881f5f6c9f1a7bfR29
a:args.input (a:context.input) seems to begin with (.
- iced#complete#candidates expects a code in parentheses, so keyword_pattern_offset may be l:keyword_pattern_offset + 1 in the following line.
1915a52#diff-e7c04951d40c1c24b7dde8bcd0db6c04f2e0911332a0efde5881f5f6c9f1a7bfR14

**Comment by kkharji** [comment]
@liquidz Can you take another look please.

**Comment by hrsh7th** [comment]
Could you update to latest nvim-compe?
It worked on my machine with vim-iced.

**Comment by hrsh7th** [comment]
For example, currently `s:complete` takes a `context` arguments but it uses `a:args` variable.
I think it will occur an exception.

**Comment by hrsh7th** [comment]
My worked procedure is below.

1. Open `vim src/hello_iced/core.clj`
2. Invoke `:IcedInstantConnect` (then `vim-iced` prints `Connected.`)
3. Edit the buffer for completion.

**Comment by kkharji** [comment]
> Could you update to latest nvim-compe?

It worked @hrsh7th thanks so much. I'm so happy it worked. I'm very grateful to you.
I'm going to push the new changes now.
